--CREATE DATABASE IDJOGOS;
CREATE TABLE PRODUTORA(
  P_CNPJ VARCHAR(18) PRIMARY KEY,
  ENDERECO VARCHAR(100)
);
CREATE TABLE DESENVOLVEDORA(
  D_CNPJ VARCHAR(18) PRIMARY KEY,
  ENDERECO VARCHAR(100),
  CHEFE_CNPJ VARCHAR(18),
  CONSTRAINT FK_CHEFE FOREIGN KEY(CHEFE_CNPJ) REFERENCES DESENVOLVEDORA(D_CNPJ)
);
CREATE TABLE TITULO(
  ID_TITULO INT PRIMARY KEY,
  D_CNPJ VARCHAR(18),
  TAMANHO VARCHAR(20),
  CLASSIFICACAO_INDICATIVA VARCHAR(10),
  CONSTRAINT FK_TITULO_DESENVOLVEDORA FOREIGN KEY(D_CNPJ) REFERENCES DESENVOLVEDORA(D_CNPJ)
);
CREATE TABLE GENERO(
  ID_TITULO INT NOT NULL,
  GENERO VARCHAR(10) NOT NULL,
  --DISCRIMINADOR
  CONSTRAINT PK_GENERO PRIMARY KEY (ID_TITULO, GENERO),
  CONSTRAINT FK_GENERO_TITULO FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO)
);
CREATE TABLE USUARIO(
  ID_USUARIO INT PRIMARY KEY,
  DATA_DE_CRIACAO_DA_CONTA TIMESTAMP,
  TEMPO_DE_PARTICIPACAO INT
);
CREATE TABLE EVENTO(
  TIMESTAMP TIMESTAMP PRIMARY KEY,
  NOME varchar(100)
);
CREATE TABLE PATROCINADOR(
  ID_PATROCINADOR INT PRIMARY KEY,
  PREMIACAO NUMBER
);
CREATE TABLE PEDIDO(
  NUMERO INT NOT NULL,
  ID_USUARIO INT NOT NULL,
  PLATAFORMA VARCHAR(10),
  VALOR NUMBER,
  CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
  CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO, ID_USUARIO)
);
-- Titutos que compõem um pedido
CREATE TABLE PEDIDOTITULO(
  ID_PEDIDO INT NOT NULL,
  ID_TITULO INT NOT NULL,
  CONSTRAINT PK_PEDIDO_TITULO PRIMARY KEY (ID_TITULO, ID_PEDIDO)
);
CREATE TABLE CONQUISTA(
  ID_CONQUISTA INT PRIMARY KEY,
  DIFICULDADES SMALLINT
);
CREATE TABLE REQUISITOS (
  ID_CONQUISTA INT NOT NULL,
  REQUISITO VARCHAR(10) NOT NULL,
  CONSTRAINT PK_REQUISITOS PRIMARY KEY (ID_CONQUISTA, REQUISITO)
);
CREATE TABLE CONQUISTA_JOGO(
  ID_CONQUISTA INT PRIMARY KEY,
  ID_TITULO INT NOT NULL,
  CONSTRAINT FK_CONQUISTA_JOGO_TITULO FOREIGN KEY (ID_TITULO) REFERENCES TITULO(ID_TITULO),
  CONSTRAINT FK_CONQUISTA_JOGO_BASE FOREIGN KEY (ID_CONQUISTA) REFERENCES CONQUISTA(ID_CONQUISTA)
);
CREATE TABLE CONQUISTA_LOJA(
  ID_CONQUISTA INT PRIMARY KEY,
  TIMESTAMP_EVENTO TIMESTAMP NOT NULL,
  CONSTRAINT FK_CONQUISTA_LOJA_EVENT FOREIGN KEY (TIMESTAMP_EVENTO) REFERENCES EVENTO(TIMESTAMP),
  CONSTRAINT FK_CONQUISTA_LOJA_BASE FOREIGN KEY (ID_CONQUISTA) REFERENCES CONQUISTA(ID_CONQUISTA)
);
CREATE TABLE POSSUI(
  ID_USUARIO INT NOT NULL,
  ID_TITULO INT NOT NULL,
  TIMESTAMP_EVENTO TIMESTAMP,
  CONSTRAINT PK_POSSUI_TITULO PRIMARY KEY (ID_TITULO, ID_USUARIO),
  CONSTRAINT FK_POSSUI_EVENTO FOREIGN KEY (TIMESTAMP_EVENTO) REFERENCES EVENTO(TIMESTAMP)
);
CREATE TABLE CAMPEONATO(
  PATROCINADOR_ID INT NOT NULL,
  TITULO_ID INT NOT NULL,
  USUARIO_ID INT NOT NULL,
  PART_TIMESTAMP TIMESTAMP,
  PART_TIME1 VARCHAR(50),
  PART_TIME2 VARCHAR(50),
  CONSTRAINT PK_CAMPEONATO PRIMARY KEY (PATROCINADOR_ID, TITULO_ID, USUARIO_ID)
);
CREATE TABLE PRODUCAO(
  D_CNPJ VARCHAR(18) NOT NULL,
  P_CNPJ VARCHAR(18) NOT NULL,
  CONSTRAINT FK_DESENVOLVE_DESENVOLVEDORA FOREIGN KEY (D_CNPJ) REFERENCES DESENVOLVEDORA(D_CNPJ),
  CONSTRAINT FK_DESENVOLVE_PRODUTORA FOREIGN KEY (P_CNPJ) REFERENCES PRODUTORA(P_CNPJ)
);
INSERT ALL INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (1, TIMESTAMP '2010-10-10 13:22:11', 9000) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (2, TIMESTAMP '2020-02-11 00:22:11', 9) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (3, TIMESTAMP '2021-04-15 18:22:11', 9) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (4, TIMESTAMP '2022-03-30 13:22:11', 10) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (5, TIMESTAMP '2021-07-25 13:22:11', 11530) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (6, TIMESTAMP '2022-03-30 13:22:11', 10) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (7, TIMESTAMP '2022-03-30 13:22:11', 0) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (8, TIMESTAMP '2022-03-30 13:22:11', 10) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (9, TIMESTAMP '2022-03-30 13:22:11', 10) INTO USUARIO (
    ID_USUARIO,
    DATA_DE_CRIACAO_DA_CONTA,
    TEMPO_DE_PARTICIPACAO
  )
VALUES (10, TIMESTAMP '2015-05-19 13:22:11', 9800)
SELECT 1
FROM DUAL;
INSERT ALL INTO PRODUTORA (P_CNPJ, ENDERECO)
VALUES ('11.222.333/0001-03', 'Vale do Estanho, 23') INTO PRODUTORA (P_CNPJ, ENDERECO)
VALUES ('44.555.666/0001-02', 'Vale do Silicio, 98')
SELECT 1
FROM DUAL;
INSERT ALL INTO DESENVOLVEDORA (D_CNPJ, ENDERECO, CHEFE_CNPJ)
VALUES ('68.378.624/0001-80', 'Rua dos Bobos, 0', NULL) INTO DESENVOLVEDORA (D_CNPJ, ENDERECO, CHEFE_CNPJ)
VALUES (
    '89.740.002/0001-20',
    'Rua dos Bobos, 1',
    '68.378.624/0001-80'
  ) INTO DESENVOLVEDORA (D_CNPJ, ENDERECO, CHEFE_CNPJ)
VALUES (
    '89.740.003/0001-20',
    'Rua dos Bobos, 2',
    '68.378.624/0001-80'
  ) INTO DESENVOLVEDORA (D_CNPJ, ENDERECO, CHEFE_CNPJ)
VALUES (
    '89.740.004/0001-20',
    'Rua dos Bobos, 3',
    '68.378.624/0001-80'
  ) INTO DESENVOLVEDORA (D_CNPJ, ENDERECO, CHEFE_CNPJ)
VALUES (
    '42.093.159/0001-48',
    'Vale do Silicio, 25',
    NULL
  )
SELECT 1
FROM DUAL;
INSERT ALL INTO PRODUCAO (D_CNPJ, P_CNPJ)
VALUES ('68.378.624/0001-80', '11.222.333/0001-03')
SELECT 1
FROM DUAL;
INSERT ALL INTO TITULO (
    ID_TITULO,
    D_CNPJ,
    TAMANHO,
    CLASSIFICACAO_INDICATIVA
  )
VALUES (1, '68.378.624/0001-80', '1mb', 'IDADE 18') INTO TITULO (
    ID_TITULO,
    D_CNPJ,
    TAMANHO,
    CLASSIFICACAO_INDICATIVA
  )
VALUES (2, '89.740.002/0001-20', '12 GBTS', 'IDADE 18') INTO TITULO (
    ID_TITULO,
    D_CNPJ,
    TAMANHO,
    CLASSIFICACAO_INDICATIVA
  )
VALUES (3, '89.740.002/0001-20', '12 GBTS', 'LIVRE') INTO TITULO (
    ID_TITULO,
    D_CNPJ,
    TAMANHO,
    CLASSIFICACAO_INDICATIVA
  )
VALUES (4, '42.093.159/0001-48', '3 GBTS', 'IDADE 14')
SELECT 1
FROM DUAL;
INSERT ALL INTO EVENTO (TIMESTAMP, NOME)
VALUES (
    TIMESTAMP '2015-10-10 00:00:00',
    'DEU A LOUCA NO PATRAO'
  ) INTO EVENTO (TIMESTAMP, NOME)
VALUES (TIMESTAMP '2022-11-16 00:00:00', 'BLACK FRIDAY')
SELECT 1
FROM DUAL;
INSERT ALL INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (1, 1, TIMESTAMP '2015-10-10 00:00:00') INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (1, 2, TIMESTAMP '2015-10-10 00:00:00') INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (1, 3, NULL) INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (1, 4, NULL) INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (2, 3, NULL) INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (2, 4, TIMESTAMP '2022-11-16 00:00:00') INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (7, 3, NULL) INTO POSSUI (ID_USUARIO, ID_TITULO, TIMESTAMP_EVENTO)
VALUES (7, 4, NULL)
SELECT 1
FROM DUAL;
INSERT ALL INTO PEDIDO (NUMERO, ID_USUARIO, PLATAFORMA, VALOR)
VALUES (1, 1, 'PC', 100) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (1, 1) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (1, 2) INTO PEDIDO (NUMERO, ID_USUARIO, PLATAFORMA, VALOR)
VALUES (2, 1, 'PC', 50) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (2, 3) INTO PEDIDO (NUMERO, ID_USUARIO, PLATAFORMA, VALOR)
VALUES (3, 1, 'PC', 50) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (3, 4) INTO PEDIDO (NUMERO, ID_USUARIO, PLATAFORMA, VALOR)
VALUES (4, 2, 'XBOX', 100) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (4, 3) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (4, 4) INTO PEDIDO (NUMERO, ID_USUARIO, PLATAFORMA, VALOR)
VALUES (5, 7, 'PS5', 100) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (5, 3) INTO PEDIDOTITULO (ID_PEDIDO, ID_TITULO)
VALUES (5, 4)
SELECT 1
FROM DUAL;
INSERT ALL INTO CONQUISTA (ID_CONQUISTA, DIFICULDADES)
VALUES (1, 10) INTO CONQUISTA_JOGO (ID_CONQUISTA, ID_TITULO)
VALUES (1, 1) INTO CONQUISTA (ID_CONQUISTA, DIFICULDADES)
VALUES (2, 15) INTO CONQUISTA_JOGO (ID_CONQUISTA, ID_TITULO)
VALUES (2, 1) INTO CONQUISTA (ID_CONQUISTA, DIFICULDADES)
VALUES (3, 5) INTO CONQUISTA_JOGO (ID_CONQUISTA, ID_TITULO)
VALUES (3, 2) INTO CONQUISTA (ID_CONQUISTA, DIFICULDADES)
VALUES (4, 5) INTO CONQUISTA_LOJA (ID_CONQUISTA, TIMESTAMP_EVENTO)
VALUES (4, TIMESTAMP '2022-11-16 00:00:00')
SELECT 1
FROM DUAL;
-- -Group by/Having
select CHEFE_CNPJ,
  count(*)
from DESENVOLVEDORA
group by CHEFE_CNPJ
having count(*) > 1;
--Junção interna
select P.ID_USUARIO,
  A.DATA_DE_CRIACAO_DA_CONTA
from TITULO T
  inner join POSSUI P on (T.ID_TITULO = P.ID_TITULO)
  inner join USUARIO A on (P.ID_USUARIO = A.ID_USUARIO)
where TEMPO_DE_PARTICIPACAO > 0;
--Junção externa
select *
from CONQUISTA_JOGO C
  full outer join TITULO T on (C.ID_CONQUISTA = T.ID_TITULO)
where C.ID_CONQUISTA is null;
--Semi junção
select *
from TITULO T
where T.D_CNPJ in (
    select D.D_CNPJ
    from DESENVOLVEDORA D
    where D.CHEFE_CNPJ is null
  );
--Anti-junção
select *
from CONQUISTA_JOGO C
where C.ID_TITULO not in (
    select T.ID_TITULO
    from TITULO T
    where T.TAMANHO = '1234 GBTS'
  );
--Subconsulta do tipo escalar
select *
from USUARIO A
where A.TEMPO_DE_PARTICIPACAO > (
    select avg(TEMPO_DE_PARTICIPACAO)
    from USUARIO
  );
--Subconsulta do tipo linha
select *
from TITULO T
where (T.TAMANHO, T.D_CNPJ) = (
    select TAMANHO,
      D_CNPJ
    from TITULO
    where ID_TITULO = 2
  );
--Subconsulta do tipo tabela
select *
from TITULO
where D_CNPJ in (
    select D_CNPJ
    from DESENVOLVEDORA
    where CHEFE_CNPJ is not null
  );
--Operação de conjunto
select P_CNPJ
from PRODUTORA
UNION
select D_CNPJ
from DESENVOLVEDORA;
CREATE OR REPLACE PROCEDURE qtd_titulos (cnpj_desenvolvedora IN VARCHAR) --Utiliza relacionamentos
  IS qtdT NUMBER;
BEGIN
SELECT COUNT(*) INTO qtdT
FROM TITULO
WHERE D_CNPJ = cnpj_desenvolvedora;
DBMS_OUTPUT.PUT_LINE('QTD:' || qtdT);
END qtd_titulos;
-- EXEC qtd_titulos('89.740.002/0001-20');
--
CREATE OR REPLACE PROCEDURE desenvolvedora_chefe (cnpj_desenvolvedora IN VARCHAR)
IS cnpj_chefe VARCHAR(18);
BEGIN
SELECT D.CHEFE_CNPJ INTO cnpj_chefe
FROM DESENVOLVEDORA D
WHERE D_CNPJ = cnpj_desenvolvedora;
CASE
  WHEN cnpj_chefe IS NULL THEN DBMS_OUTPUT.PUT_LINE('A desenvolvedora não possui chefes');
ELSE DBMS_OUTPUT.PUT_LINE(
  'A desenvolvedora é subordinada à: ' || cnpj_chefe
);
END CASE
;
END desenvolvedora_chefe;
-- EXEC desenvolvedora_chefe('89.740.002/0001-20');
-- EXEC listar_jogos_prod '11223344';